service: <+secrets.getValue("serverless_simple_website")>
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  function1:
    handler: index.handler
package:
  artifact: {{.Values.artifactPath}}
