apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-svc-primary
  annotations:
    harness.io/primary-service: "true"
spec:
  type: {{.Values.serviceType}}
  ports:
  - port: {{.Values.servicePort}}
    targetPort: {{.Values.serviceTargetPort}}
    protocol: TCP
  selector:
    app: {{.Values.name}}
