apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-svc-stage
  annotations:
    harness.io/stage-service: "true"
  labels:
    app: bg-demo-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: bg-demo-app
